### ISSUE TITLE
RESET Pin 14 on ROM to RESET or (not)RESET

### ISSUE THREAD

**Issue by KoopsF** [HDR/MBC3-Flashcart#4]
I noticed in the PCB file that the RESET/(not)RESET pin from the ROM is connected to the RESET pin from BA6129AF.
I've seen another project making a flashcard connecting the RESET pin from the ROM to the (not)RESET pin.
The other project:
https://github.com/JRodrigoTech/FLASH-ROM-Adapter-for-GameBoy
https://www.jrodrigo.net/wiki/how-to-diy-a-gameboy-flash-cartridge-with-a-rom-adapter-board/

I'm confused about where to connect the RESET pin. 
Does anybody know?

**Comment by HDR** [comment]
Please don't use github issues to ask generic support questions

**Comment by KoopsF** [comment]
don't be a bitch
